[Server]
# Уровень логирования: DEBUG, INFO, WARNING, ERROR, CRITICAL
LogLevel = INFO
Host = 0.0.0.0
Port = 8000
# Если Reload = True, сервер будет перезагружаться при изменении кода 
# (AppModule должно совпадать с названием вашего python-файла, например tts_server:app)
Reload = False
AppModule = tts_server:app

[Device]
# IP-адрес Контроллера 2 (ESP32 с динамиком) в локальной сети
ESP32_Speaker_URL = http://192.168.1.100/play

[Models]
# Пути или названия моделей Hugging Face
Russian = facebook/mms-tts-rus
English = facebook/mms-tts-eng
Hebrew = facebook/mms-tts-heb